### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by rollerozxa** [Bithack/principia#11]
At first it can be just some quick GitHub actions workflow that just compiles Principia on Linux to see that everything compiles fine on a PR or commit. It would be nice to additionally have builds for Windows and Android too so they could be tested to at least compile on all platforms even if one only develops on e.g. Linux. Of course the resulting binaries could be uploaded as build artifacts too so we'll have nightly binaries for people to try out.

**Comment by SametAhmetSahin** [comment]
I have written an example GitLab pipeline to build for Linux. Someone, or maybe even myself, could port it to GitHub Actions.

Notes: I'm still a noob with pipelines so this could definitely be improved, I'm open to any feedback!
I used the base focal image, but anyone can create a docker image with the required dependencies and use it instead.
I'm planning to do that and replace the focal image with the image where dependencies pre-installed.
I haven't tested jammy but I think it should work with no changes, at least in theory. 

here's the .gitlab-ci.yml file:
https://hastebin.skyra.pw/kizetukopu.bash

and here's the output:
![image](https://user-images.githubusercontent.com/23611868/187794451-140de606-662e-4201-8cf4-9582639927ba.png)

I might write the Windows and Android pipelines too when I get more free time. Android should be easy but I have no experience with building Windows binary pipelines.

**Comment by pajlada** [comment]
@SametAhmetSahin Here's an example C++ Multi-OS GitHub Actions build https://github.com/Chatterino/chatterino2/blob/master/.github/workflows/build.yml it uses CMake instead of Principia's build method but it should be doable to migrate.
Dependencies are managed via conan on Windows, so that might also need to be changed

**Comment by SametAhmetSahin** [comment]
I believe the packages `libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-gfx-dev libsdl2-net-dev libsdl2-ttf-dev` for Ubuntu needs to be added to the dependencies list.

**Comment by SametAhmetSahin** [comment]
I've uploaded an image to Docker Hub, under the name sametahmetsahin/principia-builder with the tag focal, to run it you would
`docker run --rm -it --name principia-builder -v "principiafolderhere:/principia" principia-builder /bin/bash`, then at the container shell cd to principia, and run the commands.
