### ISSUE TITLE
Setup cache on GH actions

### ISSUE THREAD

**Issue by griffi-gh** [Bithack/principia#118]
Currently, gh actions builds take ~15-20 minutes to complete and we can drastically reduce that by setting up caching. (for *.o and other files)
(Are there any drop-in solutions like https://github.com/Swatinem/rust-cache for C?/ if no it it can easily be implemented manally)

**Comment by rollerozxa** [comment]
MinGW builds already use caching for repository packages. I don't see why caching incremental builds would be useful though, Principia itself compiles fast enough.

**Comment by griffi-gh** [comment]
wdym github doesn't pull in anything except repo files by default

**Comment by rollerozxa** [comment]
er, I meant MSYS2. the MSYS2 action has built-in caching for repository packages that it will retrieve if new versions of the package aren't available from the MSYS2 repositories.

anyways, went and checked the build times for actions:
- **Linux**: ~2 min deps installation (no cache), ~4 min build time, ~6:30 in total
- **Windows**: ~4 min deps installation (using packages from cache), ~9 min build time (wtf?), ~15 min total
- **Android**: ~2 min deps installation, ~10 min build time (building 4 times for four architectures, understandable), ~12 min total

The Linux action doesn't produce any binaries currently, it's purely a sanity test to check that it compiles, so it's good that it finishes rather quickly so you can quickly see if something makes the compilation fail. Windows and Android produce binaries in addition to testing compilation, it's probably less important for them to finish quickly, they'll eventually finish or fail early if something is wrong.

**Comment by griffi-gh** [comment]
oh, ok that's pretty reasonable
