### ISSUE TITLE
Add JavaScript scripting support

### ISSUE THREAD

**Issue by jjwrap** [Bithack/principia#145]
Currently Principia only has scripting with Lua which is a horrible toy language with various quirks and limiations. It would be great to add support for a better, as well as faster language such as JavaScript, which would expand the capabilities of the scripting functionality of the game.

**Comment by jjwrap** [comment]
Really, are you just going to close the issue immediately just like that without any sort of discussion?

**Comment by rollerozxa** [comment]
There was a discussion, it was two messages, and now it is closed. Please read what I said.

**Comment by griffi-gh** [comment]
no, just no.

**Comment by jjwrap** [comment]
> no, just no.

Please consider it just for a moment.

**Comment by griffi-gh** [comment]
> > no, just no.
> 
> Please consider it just for a moment.

1) we already have lua scripting; there's nothing inherently wrong with lua  
2) we are not adding a whole ass js runtime to the game, and "minimalist" ones are terribly slow  
3) We are not going to maintain TWO, completely separate scripting apis

**Comment by jjwrap** [comment]
Seems like this project is being run by incompetent people.

**Comment by griffi-gh** [comment]
> Seems like this project is being run by incompetent people.

I provided multiple reasons above explaining why this feature request doesn't make any sense.

**Comment by griffi-gh** [comment]
> @rollerozxa Why are you the "project maintainer" of the game if you clearly do not know how to program? Did you buy ownership of the game and are now running it into the ground for your own amusement? All your recent commits are just removing random lines of code and adding some retarded batch file for playing community levels even though you can just play them directly from the web browser.

@rollerozxa is literally *the* developer of principia-web
