### ISSUE TITLE
There is no way to know the "Alpha" value of a "Pixel" object after switching to GTK 3.

### ISSUE THREAD

**Issue by unnamed25** [Bithack/principia#160]
In the "Pixel" object, there is a mechanism called "Alpha", by specifying a value there, you can control the pixel size through the "Transmitter" or "Mini transmitter", by specifying the "Frequency" value as in the "Alpha" value. Greater the value of the supplied signal to the "Transmitter" or "Mini transmitter" - the larger the "Pixel" became.
After switching to GTK 3, the value "Alpha" can be specified, but its value itself is no longer displayed anywhere, which is this feature can no longer be used.

Principia version: 2024.02.29
Operating system: Windows 11.

**Comment by griffi-gh** [comment]
oops... didn't realize that the new gtk3 color picker has no way of manually specifying alpha (or there's one but it's disabled)  
I'll look into it...

<img src="https://github.com/Bithack/principia/assets/45996170/5cbccc9f-8de8-490a-b740-17a1a0d22956" height="200">
