### ISSUE TITLE
Runtime setting to change main community site domain

### ISSUE THREAD

**Issue by rollerozxa** [Bithack/principia#165]
Or being able to disable connecting to a community site altogether. This should make Principia no longer have the Non-Free Network Services antifeature on F-Droid.

**Comment by griffi-gh** [comment]
also, update checks should be optional too

**Comment by rollerozxa** [comment]
> also, update checks should be optional too

Update check would also be disabled if you disable network connectivity. If some distro wants to rip out update checks independently then we can't stop them but the user deserves to be able to know if the downstream package they've obtained is outdated compared to upstream if they will be going onto principia-web to play levels.
