### ISSUE TITLE
libpng error: bad parameters to zlib

### ISSUE THREAD

**Issue by GalaxiumNation** [Bithack/principia#176]
### Principia version
(attempting to) run latest 2024.07.12 (terminal returned `principia-git is already the newest version (1720792243-1)`)

### OS / Hardware
HP HP ProBook 450 G8 Notebook PC- Platform: Linux 64bit
  - Operating system: Ubuntu Jammy 22.04.4
- GPU model:Mesa Intel® UHD Graphics (TGL GT2)

### Summary
**<details><summary>**How I installed it on Ubuntu**</summary>
<p>I had to jump through a smol hoop to get it (sorta) running on Ubuntu, since there isn't really an install option _to_ download it on Ubuntu. I had to manually download [ibjpeg62-turbo](https://packages.debian.org/sid/libjpeg62-turbo) and install that and then after running the debian instructions from https://principia-web.se/download it installed with (almost) no problem. during the `makedeb` process there was a single hiccup where it couldnt install a package because of innsufficient permissions so I installed it manually and restarted the `makedeb` process and it isntalled perfectly then.

------------------------------------------------------------------------
</p></details>
-anyway

(ran from terminal) Crashes with error "libpng error: bad parameters to zlib"

I doubt it has to do with libjpeg62-turbo, since it's coming from lib*png*? Idk. Updating my packages doesn't seem to do anything.
Help plz

### Steps to reproduce
Run Principia.

**Comment by rollerozxa** [comment]
Congratulations, you broke your system.

Please reinstall your Ubuntu and see if the error still happens without manually installing Debian packages into Ubuntu.

**Comment by GalaxiumNation** [comment]
Yea I've heard that it's not really the best idea to install debian packages on ubuntu but for me it's not that big of a deal to reinstall if it goes awry
