### ISSUE TITLE
Game doesn't point to the new website. 

### ISSUE THREAD

**Issue by SpicyForthProgrammer** [Bithack/principia#18]
Simple issue.

**Comment by Sothanforax** [comment]
If the current url instead gets put back up as a redirect to the current site, those who never change their ver installed won't have any issues grabbing new levels/logging in

**Comment by griffi-gh** [comment]
[principiagame.com](principiagame.com) should be re-routed to the principia-web website soon

**Comment by rollerozxa** [comment]
> [principiagame.com](principiagame.com) should be re-routed to the principia-web website soon

oh that totally does not give me performance anxiety 😅 would be nice if it could be temporarily changed to point directly at principia-web.se before we get things set up
