### ISSUE TITLE
"Not logged in" link is annoying 

### ISSUE THREAD

**Issue by EmberHeartshine** [Bithack/principia#181]
##### OS / Hardware

- Platform:
  - Operating system: Android 13

##### Summary

The "Not logged in" link in the top-left is super annoying and it's very easy to miss the pause button and hit it. Please either remove that link or give us the option to remove it, so I don't keep getting prompted every 3 seconds when I miss the pause button. 

##### Steps to reproduce

1. Open a level
2. Mess up
3. Try to hit Pause and miss
4. Hit "cancel" for the 5280th time

**Comment by griffi-gh** [comment]
I have never opened it by accident in multiple years..

**Comment by EmberHeartshine** [comment]
Well, I hit it at least a dozen times within the first 15-odd minutes of gameplay so it's not just a one-off misclick. It's frankly just poor design to have a button that results in a prompt in the far corner next to a frequently-used button that does not have a prompt. Samsung devices with rounded bevels are particularly susceptible to this.
