### ISSUE TITLE
Are there any old principia players out there?

### ISSUE THREAD

**Issue by Lenny-the-burger** [Bithack/principia#2]
I still have the pc version of the game installed, is there a way for old players to communicate now since the game is shut down?

Message me over discord: ׀  ᳄ MaL ׀ Lenny the burger#3588 

edit: here is an unofficial principia discord server: https://discordapp.com/invite/vBznrWm theres lile 50 ish old players on it.

**Comment by electroscientistX** [comment]
Yes, we have a WhatsApp group, just give your no. And we will add you :)

**Comment by Lenny-the-burger** [comment]
+1 647 462 2640

add me and i will delete this commemt for security reasons

**Comment by AdrianCapacite** [comment]
Yeah I'm still really missing the community and disappointed.

**Comment by electroscientistX** [comment]
We are in a group on WhatsApp!

**Comment by shantanuaryan67** [comment]
hi, i exist

**Comment by electroscientistX** [comment]
Hi shantanuaryan67!!
Feels good to know that you are alive!!
This is electro by the way

As far as I know, you weren't using Whatsapp back then...
Have you started using it? Coz we are on a WhatsApp group :)

**Comment by shantanuaryan67** [comment]
No, not yet. I'll join in June

**Comment by electroscientistX** [comment]
Good.
Also, Principia is coming back!!

**Comment by JOELwindows7** [comment]
JOELwindows7 

I create derivatives that improves original Allow Derivatives level!

Now. ☹
