### ISSUE TITLE
Settings menu looks faded on Windows 11.

### ISSUE THREAD

**Issue by SagnikDey92** [Bithack/principia#26]
Attaching a screenshot that illustrates the problem.![unknown](https://user-images.githubusercontent.com/38098355/183428271-e7ade1b1-4b77-423c-874a-92f5e86b8709.png)

**Comment by rollerozxa** [comment]
happens on linux too

![image](https://user-images.githubusercontent.com/60856959/183428739-d9423abf-2f84-462e-a6cd-09c3fa4652fb.png)

**Comment by GoldenFoxxo** [comment]
Not sure if this is related to settings unless you're talking about most user interfaces in Principia. But mine seems to be affected as well, with the button on Windows 10.
![principia_tTf8PNLzjI](https://user-images.githubusercontent.com/21147303/183549036-1ea195bb-586f-4ff9-9d73-6c3051cc2137.png)

**Comment by rollerozxa** [comment]
For some reason this gets magically fixed on Linux in the release version.

**Comment by rollerozxa** [comment]
This should be mostly fixed (custom style is only applied on release Windows builds, any other time it uses the system's GTK style)
