### ISSUE TITLE
(Bug) Robot property setting window causes hang

### ISSUE THREAD

**Issue by JOELwindows7** [Bithack/principia#38]
# Relevant Spec
- Platform = Windows. OS = Windows 11 22H2
- Intel i7-8750H

## Raw Task manager Copy
```
CPU

	Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

	Kecepatan dasar:	2,21 GHz
	Soket:	1
	Inti:	6
	Prosesor logika:	12
	Virtualisasi:	Diaktifkan
	Cache L1:	384 KB
	Cache L2:	1,5 MB
	Cache L3:	9,0 MB

	Penggunaan	34%
	Kecepatan	2,81 GHz
	Waktu aktif	0:06:41:59
	Proses	360
	Alur	4966
	Penanganan	192408
```

# How to reproduce
- compile source in Windows & launch
- Create new custom level or adventure level (which has robot)
- Spawn any robot if haven't already (such as Robot, Companion, Spike, Mini spike, bomber, launcher, cleaner)
- Press cogwheel (Object property setting for Robot) while the robot is selected
- try to interact with any option or just move its window

## Frequency
Always!

**Comment by rollerozxa** [comment]
This should have been fixed with https://github.com/Bithack/principia/commit/309e81e069002380e551a7c1e2b4ae3c84e89cca, but let me know if it still happens
