### ISSUE TITLE
Level Community not loading & Archived levels

### ISSUE THREAD

**Issue by coderkei** [Bithack/principia#42]
I have compiled the latest commit as of 12th August and it appears the level community does not load as per the screenshot below.

I was advised in some information on the principia-web.se community that this git version was using [http://archive.principiagame.com/](http://archive.principiagame.com/) for the level community but that doesn't seem to be the case and is loading https://principia-web.se instead (which doesn't appear to be working).

[This commit](https://github.com/Bithack/principia/commit/2f8f9cf9b2db4fba2ff220c08b09daa530a6c9f4) seems to be where the community URL was changed so has the plan to play archived levels been dropped?

There are a lot of levels in the archived version and it seems to currently not possible to play levels from it, but it would be greatly appreciated if this was made possible.

For the community levels error shown below, Android version was compiled on Ubuntu, device is running on Android 11

![image](https://user-images.githubusercontent.com/7037851/184434980-62ef754b-7da4-43ee-9fd7-145549fa12c4.png)

**Comment by rollerozxa** [comment]
The Git version's main community site is principia-web, but is able to play levels hosted on any domain, including the community site archive at archive.principiagame.com. This is intended to be made more prominent soon enough, but unfortunately right now the archive is broken from the game as it does not yet support HTTPS.

However principia-web does support HTTPS and should be usable on latest master if I'm not mistaken, but I have not tested the latest Android version yet. We're still working on getting things all sorted out, and Android is still a work in progress from what I can gather.

**Comment by coderkei** [comment]
Thank you for your confirmation that it is a work in progress.

**Comment by rollerozxa** [comment]
FWIW #44 should fix the webview, but setting up HTTPS on the level archive is out of my control and sdac would have to fix that.

**Comment by coderkei** [comment]
> FWIW #44 should fix the webview, but setting up HTTPS on the level archive is out of my control and sdac would have to fix that.

Do we have an update on being able to load levels from the archive? @rollerozxa @sdac

**Comment by rollerozxa** [comment]
I've set up a reverse proxy that supports HTTPS at https://archive.principia-web.se/. Currently it's in the footer of principia-web but I hope to put it more prominently once 1.5.2 beta builds are pushed out.

**Comment by coderkei** [comment]
> I've set up a reverse proxy that supports HTTPS at https://archive.principia-web.se/, as a temporary fix to access the archive. Currently it's in the footer of principia-web but I hope to put it more prominently once 1.5.2 beta builds are pushed out.

Thank you!
