### ISSUE TITLE
Linked game executable silently fails due to entry-point errors on Windows 10

### ISSUE THREAD

**Issue by 0xFC963F18DC21** [Bithack/principia#45]
After resolving a compilation error similar to #30 by reinstalling MSYS2 and the required MinGW-W64 libraries, the game successfully compiles under Windows 10 using MinGW-W64 as specified by the guide.

However, when the `go` script attempts to launch the game (or when launching manually from the MinGW-W64 prompt), it silently fails:

![WindowsTerminal_2022-08-15_14-08-53](https://user-images.githubusercontent.com/11721781/184640855-2ff08e85-9cce-4018-8f4f-0072d306970d.png)

**EDIT**: The recorded exit code is `127`.

There is no error message or anything. Launching on Windows directly (e.g. via Explorer) reveals several errors relating to symbols in the linked libraries:

![csrss_2022-08-15_14-02-06](https://user-images.githubusercontent.com/11721781/184639972-ba8f07f2-c89a-479f-b65f-2df900b02ac1.png)

![csrss_2022-08-15_14-02-08](https://user-images.githubusercontent.com/11721781/184639998-37b012fa-5aad-4c4a-adfc-44258db8932c.png)

![csrss_2022-08-15_14-02-11](https://user-images.githubusercontent.com/11721781/184640010-7d5fc425-27ab-4840-9806-18059b7afdb9.png)

![csrss_2022-08-15_14-02-01](https://user-images.githubusercontent.com/11721781/184640017-57533f3e-bdb9-4768-8761-761d35e14c9f.png)

I've tried to copy the `.dll` files mentioned in the error popups into the directory* with the game executable, but that did not fix any of the previous errors. In fact, a new `.dll`-related error pops up (**EDIT**: and it still does not fix launching it from the MinGW prompt):

![csrss_2022-08-15_14-05-55](https://user-images.githubusercontent.com/11721781/184640481-80633198-3c9d-40c9-a247-b46ee2180c79.png)

Which, like the others, do not go away when the specified `.dll` files are copied into the directory*. It is also strange as no linker errors or warnings were reported by the compiler / linker while the executable is compiling, only a few warnings in the executable source code for seemingly unrelated reasons.

I've also tried compiling on both `C:\` and `G:\` (in paths with no spaces in them on both cases) and that did not change the error.

\* The `.dll` files are directly copied from my MinGW-W64 installation, not from the invalid paths listed in the errors. **EDIT**: When inspecting the `.dll` files in question, they do in-fact contain the symbols being complained about, but for some reason they are not being read correctly.

## OS

Windows 10 Home 21H1

**Comment by GazziFX** [comment]
On my system it runs with go but fails in explorer

**Comment by 0xFC963F18DC21** [comment]
> On my system it runs with go but fails in explorer

I think #30 mentions something similar, but in my case, it refuses to run using both the `go` script and in explorer.

**Comment by rollerozxa** [comment]
The Principia Windows binary built directly from source will not work if you simply click on it in explorer, because it requires DLL files that exist in MSYS' PATH but not Windows'. Why it doesn't work inside MSYS I do not know though.
