### ISSUE TITLE
Support Apparatus on Kickstarter

### ISSUE THREAD

**Issue by shantanuaryan67** [Bithack/principia#5]
If you haven't read the mail :

The new Apparatus will happen, we just need a little nudge to get the snowball rolling!

But the media isn't realizing the size of this project, so they're not writing about it (yet). Send them a message, one by one from the list below (or pick just a few, if your time is limited), when they see that the interest is big, they will write about the game and boost the campaign!

I've already contacted them all, but they need to see that there's an actual interest from players. The more players contacting them, the better.

Don't forget to include the link to the Kickstarter page and YouTube video:

https://www.kickstarter.com/projects/emilromanus/apparatus-0?ref=74p4ea

https://www.youtube.com/watch?v=jvxJTTa5SCs

Bombarding targets:

https://www.pcgamer.com/about-pc-gamer/
https://www.androidpolice.com/contact/
https://corp.ign.com/content-team
https://www.makeuseof.com/contact/
https://www.gamezebo.com/get-reviewed/
https://www.droidgamers.com/contact-us/
https://kotaku.com/about
http://www.androidshock.com/contact/
https://www.polygon.com/contact#tip
https://www.androidauthority.com/contact/
https://www.gameinformer.com/staff
https://www.eurogamer.net/contact
https://www.rockpapershotgun.com/about-pc-gaming-rps/
https://www.gamespot.com/
https://www.destructoid.com/contact-us.phtml#contact
https://www.videogamer.com/contact-us
http://gamasutra.com/contactus
https://www.pcgamesn.com/about-us
https://www.theverge.com/a/tip-us-secure-contact-email
https://www.gamesradar.com/about-gamesradar/
https://www.gamezone.com/news/

Thanks! :-)

**Comment by JOELwindows7** [comment]
Update:
Kickstarter closed. @sdac said he should've set donation system instead
