### ISSUE TITLE
Add packaging scripts for common linux distros

### ISSUE THREAD

**Issue by Blue-Beaker** [Bithack/principia#59]
Add packaging scripts for common linux distros like debian and archlinux.
With these packaging scripts, the packages can be installed effortlessly with a package manager, without copying files and installing depends manually. And actions can also be set up for building these easily installable packages.

**Comment by rollerozxa** [comment]
There's already a buildscript for Arch, see [principia-git](https://aur.archlinux.org/packages/principia-git). There's also packaging instructions in the README which should be more than enough for a potential Debian packager to make a buildscript for e.g. a PPA.
