### ISSUE TITLE
Someone, decompile game! :)

### ISSUE THREAD

**Issue by ghost** [Bithack/principia#6]

**Comment by rollerozxa** [comment]
You could already do that with something like Cutter, the thing is that it's being reconstructed from machine code and things like function (except for the android binaries), method and variable names are gone, so it isn't very useful.

**Comment by FrAndroiddd** [comment]
i cant join :C update the Discord invite

**Comment by electroscientistX** [comment]
Are you living under a rock? The new principia is already here!

**Comment by FrAndroiddd** [comment]
:O pass me a link
