### ISSUE TITLE
Multitouch support for linux?

### ISSUE THREAD

**Issue by Blue-Beaker** [Bithack/principia#68]
I have a linux PC with touchscreen, and when I want to use it for principia, only one finger of touch input is recognized, even when "enable touch controls" option is on.
Will touch support for linux be implemented at some time future?

**Comment by sdac** [comment]
I think this can be f prixedetty easily because the issue isn't a lack of support but more so things being hardcoded for single touch input. I'll leave this issue open and might look into it at some point, but currently I don't have access to a touch device with Linux.

**Comment by Blue-Beaker** [comment]
> I think this can be f prixedetty easily because the issue isn't a lack of support but more so things being hardcoded for single touch input. I'll leave this issue open and might look into it at some point, but currently I don't have access to a touch device with Linux.

It's easy to get touchscreen on windows by connecting to it with "RD Client" on android, then run a linux VM on it so the touch can be redirected into the linux VM.

**Comment by rollerozxa** [comment]
Does the Windows version support multitouch? I have a Chromebook with touch support and can confirm it wouldn't register more than one finger press on the native Linux version. Haven't tried a Windows version in Wine yet.

**Comment by Blue-Beaker** [comment]
> Does the Windows version support multitouch? I have a Chromebook with touch support and can confirm it wouldn't register more than one finger press on the native Linux version. Haven't tried a Windows version in Wine yet.

I've tested it in virtualbox, it does support multitouch on windows, but not in wine because wine doesn't support multitouch yet.

**Comment by griffi-gh** [comment]
I'm pretty sure multitouch is hardcoded to only work on android/ios backends

**Comment by rollerozxa** [comment]
I've brought over some code from the Windows backend that I assumed was for multitouch support to the Linux backend yesterday. I tested running the Linux version on a Chromebook with touch support and multitouch appears to work now.
