### ISSUE TITLE
Archive the old levels from our principia cache!

### ISSUE THREAD

**Issue by Blue-Beaker** [Bithack/principia#7]
I've found lots of old levels under my Principia/lvl/db folder.
If you clone these levels to Principia/lvl/local , you can play or edit them in the editor.
So this maybe the caching folder for levels you've played before.

We could create an archive project for those old levels we can found, to bring them back!
If anyone has created an archive, reply here to let more players know and upload our cached levels to contribute to the project!

**Comment by rollerozxa** [comment]
Yeah, the community level cache folder contains every community level you've ever played, and the filename is the level ID of the community level. 

I started an archival project very similar to this, it can currently be downloaded [here](https://archive.org/details/community-levels-chunked.-7z). Currently it's a little bit unweidly to use but my far-fetched plan is to put them in a fork of the Flashpoint Launcher for browsing and playing them.

If you'd like to contribute to it or want to take part in some of the recent developments (like... new community site! uwu), please join the unofficial Principia Discord if you haven't already. https://discord.gg/MwjzftZ4

**Comment by ps100000** [comment]
@rollerozxa  Hey. Would it be possible to get a new invite link for the discord server? The one from your answer isn't working anymore. :|

**Comment by rollerozxa** [comment]
Oh yeah, sorry about that. Here's an invite that hopefully shouldn't expire anytime soon: https://discord.gg/vRM9UUES

**Comment by sdac** [comment]
I think I have backups of every single level ever published, looking into it this weekend.
