### ISSUE TITLE
Font issue on windows 

### ISSUE THREAD

**Issue by Daniel-Cpud** [Bithack/principia#70]
error: Error opening font cache at 'C:\Users\Pc\Principia/fonts.cache', reverting to non-cached font loading.
Unable to open font file: Couldn't open data-shared/fonts/Roboto-Bold.ttf

i checked and the font is there , it all happened when i clicked on the "allow touch control" in the menu and then i cant ./go animore , i tried uninstalling and reinstalling but i still got this issue

**Comment by Daniel-Cpud** [comment]
making a full reinstall of the master code also solved the issue , but i wanted to left it here aniway if someone has the same problem or if someone knows about the issue

**Comment by rollerozxa** [comment]
I'm assuming this was fixed? sounds like an issue of not running principia in the right directory or something
