### ISSUE TITLE
Makedeb failed to build

### ISSUE THREAD

**Issue by Blue-Beaker** [Bithack/principia#86]
Tried to build principia on Ubuntu 22.04 with makedeb:
```
git clone https://mpr.makedeb.org/principia-git
cd principia-git/
makedeb -si
```
But it always fail with an end of
```
[#] Entering fakeroot environment...
[#] Starting package()...
install: can't stat 'apparatus2' : no such file or directory
[! package()] A failure occurred in package().
    Aborting...
```
I think it's maybe because [this commit](https://github.com/Bithack/principia/commit/5625332f275cf02e71f8a6f6b9b509f7a4750a22) renamed 'apparatus2' to 'principia' but makedeb script didn't change so it still looks for 'apparatus2' and fails.

**Comment by rollerozxa** [comment]
For some reason I'm unable to push an update to the MPR that updates it. :shrug:
