### ISSUE TITLE
Cross-platform dialog UI replacement

### ISSUE THREAD

**Issue by rollerozxa** [Bithack/principia#95]
Currently, Principia uses platform specific dialog toolkits, native platform dialogs on Android/iOS and GTK2 on Windows/Linux. This causes inconsistency between platforms and raises the amount of work and duplication for a new platform if it doesn't support GTK2.

Some replacement dialog UI should be made that can be integrated into the Principia window and that is fully cross-platform. Something like [Dear Imgui](https://github.com/ocornut/imgui), but it **MUST** have decent touch support (it should be able to support standard touch gestures and not be a downgrade on Android and any other potential platforms that use touch). See [Minetest](https://play.google.com/store/apps/details?id=se.voxelmanip.rollertest)'s GUI on Android for an example of what I would not want to happen.

**Comment by griffi-gh** [comment]
ImGui is the perfect option 

NanoGUI also looks pretty cool, although it hasn't been updated in 4 years
https://github.com/wjakob/nanogui

We could also write our own gui library

**Comment by griffi-gh** [comment]
Nothing will feel like native wingets on mobile platforms without huge amount of work so I think keeping native gui on android may be a good idea.
moreover ImGui does not support multitouch.

**Comment by griffi-gh** [comment]
maybe we should just extend the built-in TMS widget system to support stuff like text input

**Comment by rollerozxa** [comment]
Superseded by #173.
