### ISSUE TITLE
Use system box2d and lua

### ISSUE THREAD

**Issue by fgaz** [Bithack/principia#96]
I'm packaging principia for NixOS, and I noticed that box2d and lua are bundled. We have those in our repository, so it'd be nice to be able to link to those instead

**Comment by fgaz** [comment]
> Box2D is customised, so that's not a good idea

:+1: 

> Devendoring Lua would be fine as long as you link against Lua 5.2 in particular for level compatibility.

That would be fine, we have multiple versions in the repo. I think pkg-config can enforce version 5.2.* with an expression like `'lua >= 5.2, lua < 5.3'`

**Comment by griffi-gh** [comment]
1) principia uses a custom, multithreaded Principia-specific box2d version based on Google's liquidfun  
2) we use Eris (yep, the same eris that's used in opencomputers) instead of regular lua5.2 for persistence, and we can't just replace it with vanilla lua/jit.
